name: First Workflow

run-name: TESTING

on:
    push:
        branches:
            - main
        tags:
            - "*"

permissions: write-all

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run a sample GitHub Action
              run: echo "This workflow ran successfully on the particular task"

            - name: Setting up go environment
              run: go version

            - name: Download Protobuf compiler (protoc)
              run: sudo apt install -y protobuf-compiler

            - name: Install gRPC Dependencies
              run: |
                  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
                  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

            - name: Add Go bin directory to PATH
              run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

            - name: Verify installation of protoc-gen-go and protoc-gen-go-grpc
              run: |
                  which protoc-gen-go
                  which protoc-gen-go-grpc

            - name: Generate proto
              run: |
                  rm -rf generated/
                  mkdir -p generated
                  protoc \
                    --proto_path=protos \
                    --go_out=generated \
                    --go_opt=paths=source_relative \
                    --go-grpc_out=generated \
                    --go-grpc_opt=paths=source_relative \
                    protos/*.proto

            - name: Commit and push changes
              run: |
                  git config user.name "iAmGreatt"
                  git config user.email "greatjohncena9@gmail.com"
                  git add generated/*
                  git commit -m "Generate protobuf code"
                  git push origin main  # Adjust branch name as necessary
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
